const configData = {
 "memSavingMethod": 1,
 "mainConfig": {
  "description": {
   "simple": "<div id=\"title\">fusus-text search</div>",
   "full": "<details id=\"titledetails\">\n  <summary id=\"title\">fusus-text search</summary>\n  <div id=\"description\"></div>\n  <a\n     id=\"makerlink\" href=\"#\"\n     class=\"logo right\"\n  ><img alt=\"maker logo\" id=\"logo\" src=\"png/maker.png\"></a>\n  <a\n     id=\"tflink\" href=\"#\"\n     class=\"logo right\"\n  ><img alt=\"Text-Fabric logo\" id=\"logo\" src=\"png/tf.png\"></a>\n  <details>\n    <summary><i>open source</i></summary>\n    <div>\n      <p>You can\n      <a id=\"packagelink\" href=\"#\"></a>\n      this web page and use it offline\n      by unzipping and double clicking <i>text-local.html</i>.\n      </p>\n      <p>This app is generated by <a id=\"generatorlink\" href=\"#\"></a>\n      based on a configuration in <a id=\"sourcelink\" href=\"#\"></a>.\n      </p>\n      <p>Written by: <a id=\"authorlink\" href=\"#\" ></a>.\n      <p>License: <a id=\"licenselink\" href=\"#\" ></a>\n      (you are free to use and modify the code).\n      </p>\n    </div>\n  </details>\n</details>"
  },
  "jobs": {
   "simple": "",
   "full": "<div id=\"jobs\">\n  <input\n    type=\"file\" name=\"imjname\" id=\"imjname\"\n    accept=\"application/json\"\n    class=\"import\"\n  >\n  <button\n    type=\"button\" class=\"medium active\" id=\"importj\"\n    title=\"import job from file\"\n  >↑</button>\n  <button\n    type=\"button\" class=\"medium active\" id=\"deletej\"\n    title=\"delete current job\"\n  >-</button>\n  <select class=\"selinp\" id=\"jchange\"></select>\n  <button\n    type=\"button\" class=\"medium active\" id=\"newj\"\n    title=\"fresh new job\"\n  >+</button>\n  <button\n    type=\"button\" class=\"medium active\" id=\"renamej\"\n    title=\"rename current job\"\n  >→</button>\n  <button\n    type=\"button\" class=\"medium active\" id=\"dupj\"\n    title=\"duplicate current job\"\n  >++</button>\n  <button\n    type=\"button\" class=\"medium active\" id=\"exportj\"\n    title=\"export job to file\"\n  >↓</button>\n</div>"
  },
  "provenance": {
   "simple": "<table>\n  <tbody>\n    <tr>\n      <td>help</td>\n      <td><a id=\"lsdocsimplelink\" href=\"#\"></a></td>\n    </tr>\n    <tr>\n      <td>data version</td>\n      <td><a id=\"datalink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>app version</td>\n      <td><span id=\"appversion\"></span></td>\n    </tr>\n  </tbody>\n</table>",
   "full": "<table>\n  <tbody>\n    <tr>\n      <td>help</td>\n      <td><a id=\"lsdoclink\" href=\"#\"></a> ; <a id=\"cheatsheetlink\" href=\"#\"></a></td>\n    </tr>\n    <tr>\n      <td>writing</td>\n      <td><a id=\"writinglink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>docs</td>\n      <td><a id=\"datadoclink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>related</td>\n      <td><a id=\"relatedlink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>data version</td>\n      <td><a id=\"datalink\" href=\"#\"></a> </td>\n    </tr>\n    <tr>\n      <td>app version</td>\n      <td><span id=\"appversion\"></span></td>\n    </tr>\n  </tbody>\n</table> <p><a id=\"issuelink\" href=\"#\" class=\"medium active\"></a>\n  please copy the version above this line\n</p>"
  }
 },
 "defs": {
  "lsVersion": "v081@2021-11-14T11:16:11",
  "dataset": "fusus",
  "client": "text",
  "org": "annotation",
  "repo": "app-fusus",
  "urls": {
   "cheatsheet": [
    "regexp cheatsheet",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet",
    "cheatsheet of regular expressions"
   ],
   "license": [
    "MIT",
    "https://mit-license.org",
    "website of MIT license"
   ],
   "maker": [
    null,
    "https://dans.knaw.nl/en/front-page?set_language=en",
    "Website of DANS = Data Archiving and Networked Services"
   ],
   "corpus": [
    null,
    "https://among.github.io/fusus/fusus/assets/lakhnawi-with-toc",
    "Online HTML as generated from PDF"
   ],
   "corpus2": [
    "Fusus",
    "https://among.github.io/fusus/fusus/assets/lakhnawi-with-toc",
    "Online HTML as generated from PDF"
   ],
   "author": [
    "Dirk Roorda",
    "https://pure.knaw.nl/portal/en/persons/dirk-roorda",
    "profile of the author"
   ],
   "author1": [
    "Cornelis van Lit",
    "https://digitalorientalist.com/about-cornelis-van-lit/",
    "lead researcher"
   ],
   "author2": [
    "Dirk Roorda",
    "https://pure.knaw.nl/portal/en/persons/dirk-roorda",
    "data modeler"
   ],
   "tf": [
    null,
    "https://annotation.github.io/text-fabric/tf/",
    "Text-Fabric documentation website"
   ],
   "lsdoc": [
    "user manual (full)",
    "https://annotation.github.io/text-fabric/tf/about/clientmanual.html",
    "user manual for the full search interface"
   ],
   "lsdocsimple": [
    "user manual (simple)",
    "https://annotation.github.io/text-fabric/tf/about/manual.html",
    "user manual for the simplified search interface"
   ],
   "datadoc": [
    "data (feature) documentation",
    "https://among.github.io/fusus/fusus/about/transcription.html",
    "explanation of the features in the dataset"
   ],
   "data": [
    "based on text-fabric data version 0.7",
    "https://github.com/among/fusus/tree/master/tf/Fusus/0.7",
    "online repository of the underlying text-fabric data"
   ],
   "generator": [
    "text-fabric/client",
    "https://annotation.github.io/text-fabric/tf/client/make/build.html",
    "the generator of this search interface"
   ],
   "source": [
    "app-fusus",
    "https://github.com/annotation/app-fusus/tree/master/layeredsearch",
    "source code of the definition of this search interface"
   ],
   "issue": [
    "Report an issue",
    "https://github.com/annotation/app-fusus/issues",
    "report issues"
   ],
   "package": [
    "download",
    "../text.zip",
    "zip file for offline use"
   ],
   "writing": [
    "ara",
    "https://annotation.github.io/text-fabric/tf/writing/ara.html",
    "characters and transliteration for ara"
   ],
   "related": [
    "text-fabric fusus",
    "https://nbviewer.jupyter.org/github/annotation/tutorials/tree/master/fusus/start.ipynb",
    "using Text-Fabric on the same corpus"
   ]
  },
  "description": "<p>Full-text search (original arabic and several transcriptions) in <a id=\"corpus2link\" href=\"#\"></a>.</p> <p>This search interface is by:</p> <ul>\n    <li><a id=\"author2link\" href=\"#\"></a> (data modeler)\n    <li><a id=\"author1link\" href=\"#\"></a> (lead researcher)\n</ul>"
 },
 "ntypes": [
  "word",
  "line",
  "piece"
 ],
 "typesLower": {
  "word": [
   "word"
  ],
  "line": [
   "word",
   "line"
  ],
  "piece": [
   "word",
   "line",
   "piece"
  ]
 },
 "defaultSettings": {
  "autoexec": true,
  "nodeseq": true,
  "exporthl": true,
  "exportsr": true,
  "multihl": true,
  "simple": false
 },
 "defaultFlags": {
  "i": true,
  "m": true,
  "s": false
 },
 "keyboard": {
  "•": "bullet",
  "≤": "less than or equal",
  "≥": "greater than or equal"
 },
 "focusType": "line",
 "ntypesinit": {
  "word": 1,
  "line": 45443,
  "piece": 50215
 },
 "ntypessize": {
  "word": 40983,
  "line": 4369,
  "piece": 29
 },
 "dtypeOf": {
  "line": "word",
  "piece": "line"
 },
 "utypeOf": {
  "word": "line",
  "line": "piece"
 },
 "visible": {
  "word": {
   "betalatin_lk": true,
   "betaascii_lk": false,
   "betalatin_af": true,
   "betaascii_af": false
  },
  "line": {
   "location": false
  },
  "piece": {
   "bezel": true,
   "title": true,
   "number": false
  }
 },
 "levels": {
  "word": "words",
  "line": "physical lines in the printed edition",
  "piece": "piece (i.e. bezel)"
 },
 "layers": {
  "word": {
   "betalatin_lk": {
    "valueMap": null,
    "tip": false,
    "pos": "betalatin_lk",
    "pattern": "",
    "description": "lakhnawi, beta code, latin with diacritics"
   },
   "betaascii_lk": {
    "valueMap": null,
    "tip": false,
    "pos": "betaascii_lk",
    "pattern": "",
    "description": "lakhnawi, beta code, ascii"
   },
   "betalatin_af": {
    "valueMap": null,
    "tip": false,
    "pos": "betalatin_af",
    "pattern": "",
    "description": "afifi, beta code, latin with diacritics"
   },
   "betaascii_af": {
    "valueMap": null,
    "tip": false,
    "pos": "betaascii_af",
    "pattern": "",
    "description": "afifi, beta code, ascii"
   }
  },
  "line": {
   "location": {
    "valueMap": null,
    "tip": false,
    "pos": "location",
    "pattern": "",
    "description": "page number:line number within the page"
   }
  },
  "piece": {
   "bezel": {
    "valueMap": [
     [
      1,
      1
     ],
     [
      2,
      1
     ],
     [
      3,
      1
     ],
     [
      4,
      1
     ],
     [
      5,
      1
     ],
     [
      6,
      1
     ],
     [
      7,
      1
     ],
     [
      8,
      1
     ],
     [
      10,
      1
     ],
     [
      11,
      1
     ],
     [
      12,
      1
     ],
     [
      13,
      1
     ],
     [
      14,
      1
     ],
     [
      15,
      1
     ],
     [
      16,
      1
     ],
     [
      17,
      1
     ],
     [
      18,
      1
     ],
     [
      19,
      1
     ],
     [
      20,
      1
     ],
     [
      21,
      1
     ],
     [
      22,
      1
     ],
     [
      23,
      1
     ],
     [
      24,
      1
     ],
     [
      25,
      1
     ],
     [
      27,
      1
     ]
    ],
    "tip": false,
    "pos": "bezel",
    "pattern": "",
    "description": "bezel number, excluding introduction"
   },
   "title": {
    "valueMap": null,
    "tip": false,
    "pos": "title",
    "pattern": "",
    "description": "title of the piece"
   },
   "number": {
    "valueMap": null,
    "tip": false,
    "pos": "number",
    "pattern": "",
    "description": "piece number, including introduction"
   }
  }
 }
}